import { jsPDF } from 'jspdf';

export const generatePDF = (name: string, complaint: string, department: string, address: string) => {
  const doc = new jsPDF();

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('CITYGUARDIAN REPORT RECEIPT', 20, 20);

  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleString()}`, 20, 30);
  doc.line(20, 35, 190, 35);

  // Report Details
  doc.setFontSize(12);
  doc.text(`Reporter: ${name}`, 20, 50);
  doc.text(`Department: ${department}`, 20, 60);
  doc.text(`Location: ${address}`, 20, 70);

  // Description
  doc.text('Description:', 20, 85);
  const splitText = doc.splitTextToSize(complaint, 160);
  doc.text(splitText, 20, 95);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by CityGuardian AI - Civic Action Platform', 20, 280);

  // Download
  doc.save(`CityGuardian_Receipt_${Date.now()}.pdf`);
};

export const saveToHistory = (reportData: any, userId: string = 'public') => {
  const key = `cg_history_${userId}`;
  const history = JSON.parse(localStorage.getItem(key) || '[]');

  const newReport = {
    id: Date.now(),
    date: new Date().toLocaleString(),
    ...reportData
  };

  history.unshift(newReport);
  localStorage.setItem(key, JSON.stringify(history.slice(0, 5)));

  return history.slice(0, 5);
};

export const getHistory = (userId: string = 'public') => {
  const key = `cg_history_${userId}`;
  return JSON.parse(localStorage.getItem(key) || '[]');
};

export const clearHistory = (userId: string = 'public') => {
  const key = `cg_history_${userId}`;
  localStorage.removeItem(key);
};
