import { jsPDF } from 'jspdf';

export const generatePDF = async (name: string, complaint: string, department: string, address: string, imageSource?: File | string | null) => {
  const doc = new jsPDF();

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('CITYGUARDIAN REPORT RECEIPT', 20, 20);

  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleString()}`, 20, 30);
  doc.line(20, 35, 190, 35);

  // Report Details
  doc.setFontSize(12);
  doc.text(`Reporter: ${name}`, 20, 50);
  doc.text(`Department: ${department}`, 20, 60);
  doc.text(`Location: ${address}`, 20, 70);

  // Description
  doc.text('Description:', 20, 85);
  const splitText = doc.splitTextToSize(complaint, 160);
  doc.text(splitText, 20, 95);

  let yPos = 95 + (splitText.length * 5) + 10;

  // Add Image if present
  if (imageSource) {
    try {
      let base64Img = '';
      if (imageSource instanceof File) {
        base64Img = await fileToBase64(imageSource);
      } else if (typeof imageSource === 'string') {
        base64Img = await urlToBase64(imageSource);
      }

      if (base64Img) {
        doc.text('Attached Evidence:', 20, yPos);
        doc.addImage(base64Img, 'JPEG', 20, yPos + 5, 100, 75); // Aspect ratio might vary, fixed for now
      }
    } catch (e) {
      console.error("Failed to add image to PDF", e);
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by CityGuardian AI - Civic Action Platform', 20, 280);

  // Download
  doc.save(`CityGuardian_Receipt_${Date.now()}.pdf`);
};

// Helper utilities for image conversion
const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = error => reject(error);
  });
};

const urlToBase64 = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    console.log("DEBUG: urlToBase64 called for:", url);
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.src = url;
    img.onload = () => {
      console.log("DEBUG: Image loaded successfully");
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      ctx?.drawImage(img, 0, 0);
      try {
        const dataURL = canvas.toDataURL('image/jpeg');
        resolve(dataURL);
      } catch (e) {
        console.error("DEBUG: Canvas toDataURL failed (CORS?):", e);
        reject(e);
      }
    };
    img.onerror = error => {
      console.error("DEBUG: Image loading failed:", error);
      reject(error);
    };
  });
};

export const saveToHistory = (reportData: any, userId: string = 'public') => {
  const key = `cg_history_${userId}`;
  const history = JSON.parse(localStorage.getItem(key) || '[]');

  const newReport = {
    id: Date.now(),
    date: new Date().toLocaleString(),
    ...reportData
  };

  history.unshift(newReport);
  localStorage.setItem(key, JSON.stringify(history.slice(0, 5)));

  return history.slice(0, 5);
};

export const getHistory = (userId: string = 'public') => {
  const key = `cg_history_${userId}`;
  return JSON.parse(localStorage.getItem(key) || '[]');
};

export const clearHistory = (userId: string = 'public') => {
  const key = `cg_history_${userId}`;
  localStorage.removeItem(key);
};
